---
title: "2021_42_fishery"
author: "Marius Grabow"
date: "14/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

package.list=c("tidyverse",
               "here",
               "showtext",
               "pdftools",
               "readr",
               "lubridate",
               "RColorBrewer",
               "ggtext",
               "extrafont",
               "png",
               "grid")

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}


font_add_google("Roboto Slab","roboto slab")
showtext_auto()
```

```{r}
fish<- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-10-12/capture-fishery-production.csv')%>%
  select(Year,production='Capture fisheries production (metric tons)')%>%
  group_by(Year)%>%
  summarise(production=sum(production))

fisher<-readPNG(here("data","fisher.png"))
g <- rasterGrob(fisher, interpolate=TRUE)


  ggplot(fish,aes(x=Year,y=production/1000000))+
  geom_line(colour="white",size=20)+
    geom_line(colour="darkblue",size=5,alpha=0.3)+
    geom_area( fill="lightblue", alpha=1)+
    geom_rect(xmin=2018,xmax=2500,ymin=0,ymax=907.5924,fill="lightblue")+
    geom_segment(aes(x=2018,xend=2018,y=0,yend=907.5924),col="grey70",linetype="dashed")+
    annotation_custom(g, xmin=2018, xmax=Inf, ymin=830, ymax=Inf)+
    coord_cartesian(xlim = c(1965, 2030),
                    ylim=c(100,1000)) +
    scale_x_continuous(breaks=c(1970,1980,1990,2000,2010,2018))+
    labs(title = "Fishing or Overfishing?",
         subtitle = " Fishing rates are increasing in freshwater & marine fishery worldwide",
         caption = "\nData from Our World in Data | Visualisation by Marius Grabow")+
  ylab("Production in Megatons [million tonnes]\n ")+
  xlab("\nYear")+
    theme(plot.margin = unit(c(1,1,1,1),"cm"),
          panel.background= element_rect(fill="#FFF4AA",colour="white"),
          panel.grid = element_blank(),
          axis.text  = element_text(size=15,color="grey60", family = "roboto slab"),
    axis.title = element_text(size=15,color="grey40", family = "roboto slab"),
    title = element_text(size=56,color="grey40", family = "roboto slab"),
    legend.title = element_text(size=10,color="grey40", family = "roboto slab"),
    plot.caption = element_text(size=10,color="grey40", family = "roboto slab"),
    plot.subtitle = element_text(size=20,color="grey40", family = "roboto slab")
    )
  
  ggsave(here("plots","2021_42_fishery.pdf"),
       width = 12, height = 12, device = cairo_pdf)

pdf_convert(pdf = here("plots","2021_42_fishery.pdf"),
                      filenames = here(
                      "plots","2021_42_fishery.png"),
                      format = "png", dpi = 450)
```

