---
title: "2021_32_Paralympics"
author: "Marius Grabow"
date: "5 8 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

package.list=c("tidyverse",
               "here",
               "showtext",
               "pdftools")

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
```

```{r}
athletes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-03/athletes.csv')%>%filter(medal=="Gold")%>%
  select(abb,year)%>%
  group_by(abb,year)%>%
  summarise(n=n())%>%
  ungroup()%>%
  group_by(abb)%>%
  mutate(total=sum(n))%>%
  filter(abb=="USA"|abb=="CHN"|abb=="GBR")%>%
  ungroup()%>%
  mutate(country=recode(abb,
                        USA="United States of America",
                        CHN="Republic of China",
                        GBR="Great Britain"))
  

cols<-c("#309f3d","#fc3517","#0059d0")
font_add_google(name="Oswald",family="oswald")
showtext.auto()

athletes%>%
  ggplot(aes(x=year,y=n,col=country))+
  geom_line(size=4)+
  scale_fill_manual(values = cols)+
  theme_void()+
  labs(title="Paralympic Gold Medal history",
       subtitle = "Changes in number of Paralympic Gold Medals \nof Top 3 countries of All Time in Paralympic Games\n",
       caption = "\n\n\nData from International Paralympic Committee | Visualisation by Marius Grabow"
    
  )+
  annotate(
    "text",y=156,x=2016+0.5, label="China",size=10,color=cols[1],
    family="oswald",hjust=0,fontface="bold"
  )+
  annotate(
    "text",y=43,x=2016+0.5, label="Great Britain",size=10,color=cols[2],
    family="oswald",hjust=0,fontface="bold"
  )+
  annotate(
    "text",y=69,x=2016+0.5, label="USA",size=10,color=cols[3],
    family="oswald",hjust=0,fontface="bold"
  )+
  scale_x_continuous(breaks=seq(1980,2016,4))+
  theme(axis.title.x = element_blank(),
        axis.text = element_text(family="oswald",size=15,
                                 colour="grey40"),
        plot.title=element_text(family="oswald",size=50,
                                face="bold"),
        plot.subtitle = element_text(family = "oswald",size=30),
        legend.title = element_blank(),
        legend.text = element_text(family="oswald",size=25,
                                   colour="grey40"),
        legend.key.size = unit(1.5,'cm'),
        plot.caption = element_text(family="oswald",size=13,
                                    hjust=1,colour="grey40"),
        plot.margin = unit(c(1,1,1,1),"cm"),
        panel.grid.minor  = element_blank(),
        legend.position = "none"
)+
  coord_cartesian(xlim=c(1980,2030),clip="off")

ggsave(here("plots","2021_32_paralympics.pdf"),
       width = 12, height = 12, device = cairo_pdf)

pdf_convert(pdf = here("plots","2021_32_paralympics.pdf"),
                      filenames = here(
                      "plots","2021_32_paralympics.png"),
                      format = "png", dpi = 450)
```

