---
title: "Untitled"
author: "Marius Grabow"
date: "13 7 2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
package.list=c("tidyverse",
               "here",
               "wesanderson",
               "lubridate",
               "ggstream",
               "waffle",
               "extrafont")

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

```

```{r}
scooby<-readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-13/Scooby-Doo%20Completed.csv',
                        na = c("", "NA"))%>%
  mutate(year=as.numeric(substr(date.aired,1,4)))%>%
  mutate(Gender=if_else(str_detect(monster.gender,"Male,Female|Female,Male"),"Mixed",monster.gender))%>%
  mutate(Gender=gsub(".*,","",Gender))%>%
  mutate(monster.species=gsub(".*,","",monster.species))%>%
  select(year,
         monster.amount,
         monster.gender,
         monster.species,
         format,
         Gender)
  

scooby%>%
  ggplot(aes(fill=Gender,values=monster.amount))+
  geom_waffle(n_rows = 30, size = 0.1, colour = "white", flip = T,)+
  scale_fill_manual(name = NULL,
                    values = c(wes_palette("Darjeeling1",4)))+
  labs(title="Gender inequality in monsters of Scooby-Doo",
       subtitle="Monster gender in order of appearance",
       caption = "Data: Kaggle | TidyTuesday")+
  coord_equal()+
  theme(
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(colour = "#373737",
                              family = "Berlin Sans FB Demi",
                              size=25,
                              hjust = 1),
    plot.subtitle = element_text(colour = "#b1b1b1",
                                 family = "Berlin Sans FB Demi",
                                 hjust=0.05,
                                 size=18),
    plot.caption = element_text(colour = "#b1b1b1",hjust=0.5),
    axis.text =element_blank(),
    legend.text = element_text(colour = "#373737",
                               size=15),
    axis.ticks = element_blank()
  )

ggsave(here("plots","2021_29_scooby_doo.pdf"),width = 12, height = 9,dpi=300,device=cairo_pdf)
```

